@startmindmap "Key Vault"

+ Key Vault
++ management of
+++_ secrets
+++_ keys (encryption)
+++_ certificates (SSL/TLS)
++ 2 types
+++_ Vaults
+++_ Managed HSM Pools

++ Benefits
+++_ Centralized application secrets
+++_ Securely stores secrets + keys (AAD)
++++_ RBAC - vault management
++++_ Key Vault access policy\n(stored access policy)\n - vault access
+++_ Simplified administration of secrets
+++_ Monitor access and use
++++_ configure to
+++++_ Archive to storage account
+++++_ Stream to event hub
+++++_ Send logs to Azure Monitor logs

++ Best Practices
+++ Authentication
++++_ Managed identities
++++_ Service principal
+++++_ and certificate
+++++_ and secret
+++_ Encryption of data in transit (TLS)
+++ Other
++++_ Use seperate key Vaults
++++_ Control access to vault
++++_ Backup
++++_ Recovery options
++++_ Logging
++ Authenticate with AAD
+++_ Managed Identity recommended
+++_ Otherwise, register w/ AD tenant\napplication object identifies across tenants
+++ Options
++++_ Authenticate to Key Vault with REST
++++_ Authenticate to Key Vault in application code\nSDKs for Python, .NET, Java, JavaScript
++ Service Tiers
+++_ Standard - encrypted with software key
+++_ Premium - HSM protected keys\nHardware protection of vault

@endmindmap