
@startmindmap

+ Microservices



++ Advantages

+++ System designs mirror organizational communication structure
+++ Align architecture\nwith organization
++++ means
+++++ Align ownerships of assets\nto independent teams
++++++ Team in SA does Shipping
++++++ Team in UK does Inventory
++++ allows
+++++ Organization to manage rapid growth
+++++ Dealing with teams in remote locations
++++ matches
+++++ Course grained communication of teams
+++++ course grained integration between components
++++ when not aligned
+++++ creates tension

+++ Release functionality faster
++++ Less risk
+++++ Deployment often
+++++ Change one service

+++ Independent scaling
++++ Scale one service up or down as needed

+++ Easier to focus on security concerns
++++ Apply security where it is needed
+++++ size to fit
++++++ Sensitive services
++++++ Less sensitive services

+++ Adopt new technology faster
++++ Seperate deployable units in
+++++ Go
+++++ Ruby
+++++ NodeJS
+++++ Java
++++ Explore with less important components
+++++ Small reporting dashboard

+++ Embrace uncertain digital future
++++ What type of interfaces, wearable devices to cater for?
++++ with finer grained APIs
+++++ more opportunity to adapt

@endmindmap
