
@startmindmap "Principles"
' 12 factor app
' https://12factor.net/

+ Principles of Microservices
-- Modelled around a business domain
-- Highly observable
---_ understand what is happening in the complex topology
-- Isolate Failure
---_ avoid/handle cascading failures  to achieve resliency
-- Consumer first
---_ Think from the outside, in!
++ Culture of automation
+++_ Large number of moving parts
++ Hide implementation details
+++_ Services must evolve independently from one another
++ Decentralize all things
+++_ to enable autonomy
++ Deploy independently
+++_ change and release without side-effects 

@endmindmap
